### ISSUE TITLE
rake simple_roles_engine:install:migrations isn't available

### ISSUE THREAD

**Issue by jcoyne** [stanislaw/simple_roles#5]
`Don't know how to build task 'simple_roles_engine:install:migrations'`

using simple_roles-0.0.10

**Comment by stanislaw** [comment]
Please tell what version of Rails you are using.

**Comment by jcoyne** [comment]
I'm using rails version 3.2.13

**Comment by stanislaw** [comment]
Yes, I see, that rake -T in fresh Rails 3.2.13 app folder does not have `simple_roles_engine:install:migrations` task. I haven't use Rails and specifically simple_roles for a half of a year, so I believe something has been changed in a way how Rails engines load tasks like this one. I need to take a closer look at it. Feel free to suggest a pull request if you know how it should be done now.

**Comment by stanislaw** [comment]
I found the problem, will release 0.0.11 soon.

**Comment by stanislaw** [comment]
It is done in 0.0.11.
